# Generated by Django 5.2.3 on 2025-06-18 20:20

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الدفعة')),
                ('payment_type', models.CharField(choices=[('incoming', 'وارد'), ('outgoing', 'صادر')], max_length=10, verbose_name='نوع الدفعة')),
                ('payment_method', models.CharField(choices=[('smart_wallet', 'Smart Wallet'), ('instapay', 'InstaPay'), ('bank_transfer', 'تحويل بنكي'), ('cash', 'كاش')], max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('cancelled', 'ملغي')], default='pending', max_length=10, verbose_name='الحالة')),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الدفعة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=50, unique=True, verbose_name='رقم أمر الشراء')),
                ('order_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الأمر')),
                ('expected_delivery_date', models.DateField(verbose_name='تاريخ التسليم المتوقع')),
                ('actual_delivery_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التسليم الفعلي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'معلق'), ('approved', 'موافق عليه'), ('in_delivery', 'قيد التسليم'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='draft', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المجموع الفرعي')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الضريبة')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='مبلغ الخصم')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التسليم')),
                ('delivery_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التسليم')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='ملاحظات التسليم')),
                ('quality_check_passed', models.BooleanField(default=True, verbose_name='اجتاز فحص الجودة')),
                ('quality_notes', models.TextField(blank=True, verbose_name='ملاحظات الجودة')),
                ('is_complete', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تسليم أمر شراء',
                'verbose_name_plural': 'تسليمات أوامر الشراء',
                'ordering': ['-delivery_date'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderDeliveryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delivered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المسلمة')),
                ('quality_approved', models.BooleanField(default=True, verbose_name='جودة معتمدة')),
                ('quality_notes', models.TextField(blank=True, verbose_name='ملاحظات الجودة')),
            ],
            options={
                'verbose_name': 'عنصر تسليم أمر شراء',
                'verbose_name_plural': 'عناصر تسليمات أوامر الشراء',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المطلوبة')),
                ('quantity_received', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الكمية المستلمة')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='السعر الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'عنصر أمر شراء',
                'verbose_name_plural': 'عناصر أوامر الشراء',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المورد')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود المورد')),
                ('supplier_type', models.CharField(choices=[('fabric', 'مورد أقمشة'), ('thread', 'مورد خيوط'), ('accessories', 'مورد إكسسوارات'), ('mixed', 'مورد متنوع')], max_length=20, verbose_name='نوع المورد')),
                ('contact_person', models.CharField(max_length=100, verbose_name='الشخص المسؤول')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='اسم البنك')),
                ('account_number', models.CharField(blank=True, max_length=50, verbose_name='رقم الحساب')),
                ('account_holder_name', models.CharField(blank=True, max_length=100, verbose_name='اسم صاحب الحساب')),
                ('supported_payment_methods', models.JSONField(default=list, verbose_name='طرق الدفع المدعومة')),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='حد الائتمان')),
                ('payment_terms_days', models.PositiveIntegerField(default=30, verbose_name='مدة السداد بالأيام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('current_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تعديل')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردين',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('position', models.CharField(max_length=100, verbose_name='المنصب')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('is_primary', models.BooleanField(default=False, verbose_name='جهة الاتصال الأساسية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
            ],
            options={
                'verbose_name': 'جهة اتصال المورد',
                'verbose_name_plural': 'جهات اتصال الموردين',
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('contract', 'عقد'), ('certificate', 'شهادة'), ('license', 'ترخيص'), ('tax_card', 'بطاقة ضريبية'), ('commercial_register', 'سجل تجاري'), ('other', 'أخرى')], max_length=20, verbose_name='نوع المستند')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='supplier_documents/', verbose_name='الملف')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
            ],
            options={
                'verbose_name': 'مستند مورد',
                'verbose_name_plural': 'مستندات الموردين',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierPerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='إجمالي الأوامر')),
                ('completed_orders', models.PositiveIntegerField(default=0, verbose_name='الأوامر المكتملة')),
                ('on_time_deliveries', models.PositiveIntegerField(default=0, verbose_name='التسليمات في الوقت')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='إجمالي المبلغ')),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل الإكمال')),
                ('on_time_delivery_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل التسليم في الوقت')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط التقييم')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الحساب')),
            ],
            options={
                'verbose_name': 'مقياس أداء المورد',
                'verbose_name_plural': 'مقاييس أداء الموردين',
                'ordering': ['-period_end'],
            },
        ),
        migrations.CreateModel(
            name='SupplierRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الجودة')),
                ('delivery_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم التسليم')),
                ('price_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم السعر')),
                ('service_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الخدمة')),
                ('communication_rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم التواصل')),
                ('overall_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='التقييم الإجمالي')),
                ('comments', models.TextField(blank=True, verbose_name='تعليقات')),
                ('season', models.CharField(blank=True, max_length=50, verbose_name='الموسم')),
                ('rating_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقييم')),
            ],
            options={
                'verbose_name': 'تقييم مورد',
                'verbose_name_plural': 'تقييمات الموردين',
                'ordering': ['-rating_date'],
            },
        ),
    ]
