# Generated by Django 5.2.3 on 2025-06-18 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='وافق عليه'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='payment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='suppliers.purchaseorder', verbose_name='أمر الشراء'),
        ),
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='suppliers.purchaseorder', verbose_name='أمر الشراء'),
        ),
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='received_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='استلم بواسطة'),
        ),
        migrations.AddField(
            model_name='purchaseorderdelivery',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.warehouse', verbose_name='المخزن'),
        ),
        migrations.AddField(
            model_name='purchaseorderdeliveryitem',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorderdelivery', verbose_name='التسليم'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.product', verbose_name='المنتج'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='suppliers.purchaseorder', verbose_name='أمر الشراء'),
        ),
        migrations.AddField(
            model_name='purchaseorderdeliveryitem',
            name='purchase_order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suppliers.purchaseorderitem', verbose_name='عنصر أمر الشراء'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشأ بواسطة'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='suppliers.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='payment',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='suppliers.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='suppliercontact',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='suppliers.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='suppliers.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='supplierdocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة'),
        ),
        migrations.AddField(
            model_name='supplierperformancemetric',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='suppliers.supplier', verbose_name='المورد'),
        ),
        migrations.AddField(
            model_name='supplierrating',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='suppliers.purchaseorder', verbose_name='أمر الشراء'),
        ),
        migrations.AddField(
            model_name='supplierrating',
            name='rated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='قيم بواسطة'),
        ),
        migrations.AddField(
            model_name='supplierrating',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='suppliers.supplier', verbose_name='المورد'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorderitem',
            unique_together={('purchase_order', 'product')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierperformancemetric',
            unique_together={('supplier', 'period_start', 'period_end')},
        ),
        migrations.AlterUniqueTogether(
            name='supplierrating',
            unique_together={('supplier', 'purchase_order')},
        ),
    ]
