# Generated by Django 5.2.3 on 2025-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='instapay_identifier',
            field=models.CharField(blank=True, max_length=100, verbose_name='معرف InstaPay'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='smart_wallet_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم Smart Wallet'),
        ),
    ]
