# Generated by Django 5.2.3 on 2025-07-23 06:56

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الفئة')),
                ('category_type', models.CharField(choices=[('asset', 'الأصول'), ('liability', 'الخصوم'), ('equity', 'حقوق الملكية'), ('revenue', 'الإيرادات'), ('expense', 'المصروفات')], max_length=10, verbose_name='نوع الفئة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'فئة حساب',
                'verbose_name_plural': 'فئات الحسابات',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الحساب')),
                ('code', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='الكود')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('owner_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='finance.accountcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات (دليل الحسابات)',
                'ordering': ['category', 'name'],
                'unique_together': {('owner_content_type', 'owner_object_id')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ المصروف')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
                ('expense_account', models.ForeignKey(limit_choices_to={'category__category_type': 'expense'}, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='finance.account', verbose_name='حساب المصروف')),
                ('source_account', models.ForeignKey(limit_choices_to={'category__category_type': 'asset'}, on_delete=django.db.models.deletion.PROTECT, related_name='source_of_expenses', to='finance.account', verbose_name='حساب المصدر (نقدي/بنك)')),
            ],
            options={
                'verbose_name': 'مصروف',
                'verbose_name_plural': 'المصروفات',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم الفاتورة/الوصل')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسلة'), ('received', 'مستلمة'), ('paid', 'مدفوعة بالكامل'), ('partial', 'مدفوعة جزئياً'), ('void', 'ملغاة')], default='draft', max_length=10, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('recipient_object_id', models.PositiveIntegerField()),
                ('recipient_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'فاتورة / وصل',
                'verbose_name_plural': 'الفواتير والوصولات',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('bank', 'تحويل بنكي'), ('cheque', 'شيك')], max_length=50, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, max_length=100, verbose_name='مرجع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255, verbose_name='الوصف')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='التاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='توقيت الإنشاء')),
                ('source_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'الحركات المالية (دفتر اليومية)',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='مدين')),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='دائن')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_details', to='finance.account', verbose_name='الحساب')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='finance.transaction', verbose_name='الحركة المالية')),
            ],
            options={
                'verbose_name': 'تفاصيل الحركة',
                'verbose_name_plural': 'تفاصيل الحركات',
                'ordering': ['transaction', 'debit'],
            },
        ),
    ]
