# Generated by Django 5.2.3 on 2025-07-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الحساب')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='الرصيد الحالي')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('DEPOSIT', 'إيداع'), ('WITHDRAWAL', 'سحب'), ('TRANSFER', 'تحويل')], max_length=10, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='المبلغ')),
                ('description', models.TextField(verbose_name='السبب / الوصف')),
                ('reference', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرجع (اختياري)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='finance.account', verbose_name='الحساب')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='finance.account', verbose_name='إلى حساب')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'الحركات المالية',
                'ordering': ['-timestamp'],
            },
        ),
    ]
