# Generated by Django 5.2.3 on 2025-07-31 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('finance', '0001_initial'),
        ('production', '0023_rename_size_groups_billofmaterials_size_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('ASSET', 'أصل (خزينة/بنك)'), ('LIABILITY', 'التزام (مورد/مصنع)'), ('EXPENSE', 'مصروفات'), ('REVENUE', 'إيرادات')], default='ASSET', max_length=20, verbose_name='نوع الحساب'),
        ),
        migrations.AddField(
            model_name='account',
            name='manufacturer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finance_account', to='production.externalmanufacturer', verbose_name='المصنع الخارجي المرتبط'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='الرصيد الحالي'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('DEPOSIT', 'إيداع'), ('WITHDRAWAL', 'سحب'), ('TRANSFER', 'تحويل'), ('MANUFACTURING_DEBT', 'تسجيل تكلفة تصنيع'), ('MANUFACTURER_PAYMENT', 'دفعة لمصنع')], max_length=20, verbose_name='نوع الحركة'),
        ),
    ]
