# Generated by Django 5.2.3 on 2025-09-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_account_account_type_account_manufacturer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counted_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المعدود')),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الرصيد الدفتري')),
                ('difference', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='الفرق (عجز/زيادة)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الجرد')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('account', models.ForeignKey(limit_choices_to={'account_type': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='الحساب')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الجرد')),
            ],
            options={
                'verbose_name': 'جرد خزينة',
                'verbose_name_plural': 'جرد الخزائن',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CustodyHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_handed_over', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ المسلَّم')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسليم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('account', models.ForeignKey(limit_choices_to={'account_type': 'ASSET'}, on_delete=django.db.models.deletion.PROTECT, to='finance.account', verbose_name='الحساب (العهدة)')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_from', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المُسلِّم')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_to', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المُستلِم')),
            ],
            options={
                'verbose_name': 'محضر تسليم عهدة',
                'verbose_name_plural': 'محاضر تسليم العهد',
                'ordering': ['-timestamp'],
            },
        ),
    ]
