# Generated by Django 5.2.3 on 2025-06-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='additional_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='production/attachments/', verbose_name='مرفقات'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='customer_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='مرجع العميل'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='delivery_location',
            field=models.CharField(blank=True, max_length=200, verbose_name='موقع التسليم'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='expected_completion_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الإنجاز المتوقع'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='fabric_image',
            field=models.ImageField(blank=True, null=True, upload_to='production/fabric_images/', verbose_name='صورة القماش'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='is_rush_order',
            field=models.BooleanField(default=False, verbose_name='أمر عاجل'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='minimum_stock_level',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأدنى للمخزون (متر)'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quality_check_required',
            field=models.BooleanField(default=True, verbose_name='فحص الجودة مطلوب'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quality_level',
            field=models.CharField(choices=[('standard', 'عادي'), ('premium', 'ممتاز'), ('luxury', 'فاخر')], default='standard', max_length=20, verbose_name='مستوى الجودة'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='quality_requirements',
            field=models.TextField(blank=True, verbose_name='متطلبات الجودة'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='special_instructions',
            field=models.TextField(blank=True, verbose_name='تعليمات خاصة'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت البدء'),
        ),
    ]
