# Generated by Django 5.2.3 on 2025-06-22 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionorder_additional_notes_and_more'),
        ('warehouses', '0005_add_unit_new_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textilestock',
            name='length_available',
        ),
        migrations.AddField(
            model_name='textilestock',
            name='warehouse_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='textile_equivalent', to='warehouses.product', verbose_name='منتج المخزن المرتبط'),
        ),
    ]
