# Generated by Django 5.2.3 on 2025-06-22 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_textilestock_length_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم مجموعة المقاسات')),
                ('sizes', models.JSONField(default=list, verbose_name='المقاسات')),
            ],
            options={
                'verbose_name': 'مجموعة مقاسات',
                'verbose_name_plural': 'مجموعات المقاسات',
            },
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='fabric_requirement_per_piece',
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='fabric_per_meter',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='متطلبات القماش لكل متر'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='fabric_quantity_per_piece',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='كمية القماش المطلوبة لإنتاج قطعة واحدة'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='production.productcategory', verbose_name='الفئة الأساسية')),
            ],
            options={
                'verbose_name': 'فئة المنتج',
                'verbose_name_plural': 'فئات المنتجات',
            },
        ),
        migrations.AlterField(
            model_name='finishedproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.productcategory', verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='finishedproduct',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.sizegroup', verbose_name='مجموعة المقاسات'),
        ),
    ]
