# Generated by Django 5.2.3 on 2025-06-23 16:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_sizegroup_and_more'),
        ('warehouses', '0005_add_unit_new_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # 1. First, explicitly remove the old unique_together constraint from the BillOfMaterials model.
        #    The original constraint was ('product', 'size').
        migrations.AlterUniqueTogether(
            name='billofmaterials',
            unique_together=set(),
        ),

        # 2. Now that the constraint is removed, it is safe to remove the 'size' field.
        migrations.RemoveField(
            model_name='billofmaterials',
            name='size',
        ),

        # Remove the other old fields
        migrations.RemoveField(
            model_name='billofmaterials',
            name='buttons_cost',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='buttons_count',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='fabric_cost',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='fabric_meters',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='other_materials_cost',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='thread_cost',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='thread_meters',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='total_material_cost',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='zipper_cost',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='zipper_length',
        ),

        # 3. Add the new fields to BillOfMaterials
        migrations.AddField(
            model_name='billofmaterials',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم إنشاؤه بواسطة'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='الإصدار النشط'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='production.billofmaterials', verbose_name='الإصدار السابق'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='production.sizegroup', verbose_name='مجموعة المقاسات'),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='الإصدار'),
        ),

        # 4. Now that the 'version' field is added, we can set the ordering
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['-version'], 'verbose_name': 'قائمة المواد', 'verbose_name_plural': 'قوائم المواد'},
        ),
        
        # 5. And finally, create the new unique_together constraint
        migrations.AlterUniqueTogether(
            name='billofmaterials',
            unique_together={('product', 'size_group', 'version')},
        ),

        # Continue with other operations
        migrations.AddField(
            model_name='finishedproduct',
            name='warehouse_product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finished_product_origin', to='warehouses.product', verbose_name='منتج المخزن'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='bom_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.billofmaterials', verbose_name='نسخة قائمة المواد'),
        ),
        migrations.AlterField(
            model_name='assemblyprocess',
            name='production_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assembly_processes', to='production.productionorder', verbose_name='أمر الإنتاج'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='production.finishedproduct', verbose_name='المنتج النهائي'),
        ),
        migrations.AlterField(
            model_name='dyeingprocess',
            name='assembly_process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dyeing_processes', to='production.assemblyprocess', verbose_name='عملية التجميع'),
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='الكمية')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='ملاحظات')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.billofmaterials', verbose_name='قائمة المواد')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_items', to='warehouses.product', verbose_name='المادة الخام')),
            ],
            options={
                'verbose_name': 'عنصر قائمة المواد',
                'verbose_name_plural': 'عناصر قائمة المواد',
                'unique_together': {('bom', 'material')},
            },
        ),
    ]