# Generated by Django 5.2.3 on 2025-06-24 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_add_size_group_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingprocess',
            name='marker_details',
            field=models.JSONField(blank=True, null=True, verbose_name='تفاصيل الرسمة'),
        ),
        migrations.AlterField(
            model_name='cutpiece',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الطول (سم)'),
        ),
        migrations.AlterField(
            model_name='cutpiece',
            name='piece_type',
            field=models.CharField(max_length=100, verbose_name='نوع القطعة'),
        ),
        migrations.AlterField(
            model_name='cutpiece',
            name='size',
            field=models.CharField(max_length=20, verbose_name='المقاس'),
        ),
        migrations.AlterField(
            model_name='cutpiece',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='العرض (سم)'),
        ),
        migrations.AlterUniqueTogether(
            name='cutpiece',
            unique_together={('cutting_process', 'piece_type', 'size')},
        ),
        migrations.AddIndex(
            model_name='cutpiece',
            index=models.Index(fields=['cutting_process', 'piece_type', 'size'], name='production__cutting_1ef6b3_idx'),
        ),
    ]
