# Generated by Django 5.2.3 on 2025-06-24 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_cuttingprocess_marker_details_alter_cutpiece_length_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GarmentDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='المقاس')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='production.billofmaterials', verbose_name='قائمة المواد (BOM)')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'رسمة قص',
                'verbose_name_plural': 'رسومات القص',
                'ordering': ['bom', 'size'],
                'unique_together': {('bom', 'size')},
            },
        ),
        migrations.CreateModel(
            name='DrawPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='اسم القطعة')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('draw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='production.garmentdraw', verbose_name='رسمة القص')),
            ],
            options={
                'verbose_name': 'قطعة في الرسمة',
                'verbose_name_plural': 'قطع الرسمة',
                'ordering': ['name'],
            },
        ),
    ]
