# Generated by Django 5.2.3 on 2025-06-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_garmentdraw_drawpiece'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuttingprocess',
            name='single_layer_fabric_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='طول فرشة الطبقة الواحدة'),
        ),
        migrations.AddField(
            model_name='cuttingprocess',
            name='single_layer_meterage',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='ميتراج القطعة للطبقة الواحدة'),
        ),
        migrations.AddField(
            model_name='cuttingprocess',
            name='single_layer_pieces',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد القطع في الطبقة الواحدة'),
        ),
        migrations.AddField(
            model_name='cuttingprocess',
            name='single_layer_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='عرض فرشة الطبقة الواحدة'),
        ),
    ]
