# Generated by Django 5.2.3 on 2025-06-26 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_cuttingprocess_single_layer_fabric_length_and_more'),
        ('warehouses', '0005_add_unit_new_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='externalmanufacturer',
            options={'ordering': ['name'], 'verbose_name': 'مصنع خارجي', 'verbose_name_plural': 'المصانع الخارجية'},
        ),
        migrations.AddField(
            model_name='dyeingprocess',
            name='quality_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='production/dyeing_quality/', verbose_name='صورة الجودة 1'),
        ),
        migrations.AddField(
            model_name='dyeingprocess',
            name='quality_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='production/dyeing_quality/', verbose_name='صورة الجودة 2'),
        ),
        migrations.AddField(
            model_name='dyeingprocess',
            name='quality_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='production/dyeing_quality/', verbose_name='صورة الجودة 3'),
        ),
        migrations.AddField(
            model_name='dyeingprocess',
            name='quality_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='production/dyeing_quality/', verbose_name='صورة الجودة 4'),
        ),
        migrations.AddField(
            model_name='finishingprocess',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse', verbose_name='المخزن النهائي'),
        ),
        migrations.AlterField(
            model_name='exitpermit',
            name='permit_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='رقم التصريح'),
        ),
        migrations.AlterField(
            model_name='exitpermit',
            name='permit_type',
            field=models.CharField(choices=[('cutting_materials', 'مواد القص'), ('assembly_pieces', 'قطع التجميع'), ('dyeing_garments', 'ملابس الصباغة'), ('finishing_products', 'منتجات التشطيب'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التصريح'),
        ),
        migrations.AlterField(
            model_name='exitpermit',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('used', 'مستخدم'), ('expired', 'منتهي الصلاحية')], default='pending', max_length=10, verbose_name='الحالة'),
        ),
    ]
