# Generated by Django 5.2.3 on 2025-06-26 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_alter_externalmanufacturer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitpermit',
            name='assembly_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_permits', to='production.assemblyprocess', verbose_name='عملية التجميع المرتبطة'),
        ),
    ]
