# Generated by Django 5.2.3 on 2025-06-26 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_exitpermit_assembly_process'),
        ('warehouses', '0005_add_unit_new_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المرسلة')),
                ('assembly_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.assemblyprocess', verbose_name='عملية التجميع')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.product', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'مكون تجميع مرسل',
                'verbose_name_plural': 'مكونات التجميع المرسلة',
                'unique_together': {('assembly_process', 'material')},
            },
        ),
    ]
