# Generated by Django 5.2.3 on 2025-06-27 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_assemblycomponent'),
        ('warehouses', '0006_warehouse_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblycomponent',
            name='source_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse', verbose_name='المخزن المصدر'),
        ),
    ]
