# Generated by Django 5.2.3 on 2025-06-27 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_assemblycomponent_source_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyeingprocess',
            name='quality_image_1',
        ),
        migrations.RemoveField(
            model_name='dyeingprocess',
            name='quality_image_2',
        ),
        migrations.RemoveField(
            model_name='dyeingprocess',
            name='quality_image_3',
        ),
        migrations.RemoveField(
            model_name='dyeingprocess',
            name='quality_image_4',
        ),
        migrations.AddField(
            model_name='exitpermit',
            name='dyeing_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_permits', to='production.dyeingprocess', verbose_name='عملية الصباغة المرتبطة'),
        ),
        migrations.AlterField(
            model_name='dyeingprocess',
            name='dyeing_facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dyeing_jobs', to='production.externalmanufacturer', verbose_name='مصنع الصباغة'),
        ),
        migrations.AlterField(
            model_name='exitpermit',
            name='permit_type',
            field=models.CharField(choices=[('cutting_materials', 'مواد القص'), ('assembly_pieces', 'قطع التجميع'), ('dyeing_garments', 'ملابس للصباغة'), ('finishing_products', 'منتجات التشطيب'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التصريح'),
        ),
    ]
