# Generated by Django 5.2.3 on 2025-06-27 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_remove_dyeingprocess_quality_image_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finishingprocess',
            name='finishing_cost_per_piece',
        ),
        migrations.AddField(
            model_name='exitpermit',
            name='finishing_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exit_permits', to='production.finishingprocess', verbose_name='عملية التشطيب المرتبطة'),
        ),
        migrations.AddField(
            model_name='finishingprocess',
            name='external_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_jobs', to='production.externalmanufacturer', verbose_name='المصنع الخارجي'),
        ),
        migrations.AddField(
            model_name='finishingprocess',
            name='finisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finishing_processes', to=settings.AUTH_USER_MODEL, verbose_name='مسؤول التشطيب الداخلي'),
        ),
        migrations.AddField(
            model_name='finishingprocess',
            name='finishing_type',
            field=models.CharField(choices=[('in_house', 'داخلي'), ('outsourced', 'خارجي')], default='in_house', max_length=15, verbose_name='نوع التشطيب'),
        ),
        migrations.AlterField(
            model_name='finishingprocess',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_finishing_processes', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
    ]
