# Generated by Django 5.2.3 on 2025-06-27 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_remove_finishingprocess_finishing_cost_per_piece_and_more'),
        ('warehouses', '0006_warehouse_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishingComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الكمية المرسلة')),
                ('finishing_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='production.finishingprocess', verbose_name='عملية التشطيب')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouses.product', verbose_name='المادة')),
                ('source_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouses.warehouse', verbose_name='المخزن المصدر')),
            ],
            options={
                'verbose_name': 'مكون تشطيب مرسل',
                'verbose_name_plural': 'مكونات التشطيب المرسلة',
                'unique_together': {('finishing_process', 'material')},
            },
        ),
    ]
