# Generated by Django 5.2.3 on 2025-06-28 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_finishingcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualitycontrolcheck',
            name='assembly_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.assemblyprocess', verbose_name='عملية التجميع'),
        ),
        migrations.AddField(
            model_name='qualitycontrolcheck',
            name='cutting_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.cuttingprocess', verbose_name='عملية القص'),
        ),
        migrations.AddField(
            model_name='qualitycontrolcheck',
            name='dyeing_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.dyeingprocess', verbose_name='عملية الصباغة'),
        ),
        migrations.AddField(
            model_name='qualitycontrolcheck',
            name='finishing_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quality_checks', to='production.finishingprocess', verbose_name='عملية التشطيب'),
        ),
        migrations.AlterField(
            model_name='qualitycontrolcheck',
            name='items_failed',
            field=models.PositiveIntegerField(default=0, verbose_name='العناصر المرفوضة'),
        ),
    ]
