# Generated by Django 5.2.3 on 2025-06-30 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_qualitycontrolcheck_assembly_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalproduct',
            name='product_code',
            field=models.CharField(blank=True, max_length=200, verbose_name='كود المنتج النهائي'),
        ),
    ]
