# Generated by Django 5.2.3 on 2025-07-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_finalproduct_product_code'),
        ('warehouses', '0007_productbatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalproduct',
            name='finishing_process',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='stored_by',
        ),
        migrations.RemoveField(
            model_name='finalproduct',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='size_group',
        ),
        migrations.RemoveField(
            model_name='finishedproduct',
            name='warehouse_product',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'finished'}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='product',
            field=models.ForeignKey(limit_choices_to={'product_type': 'finished'}, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='warehouses.product', verbose_name='المنتج النهائي'),
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='textilestock',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='textilestock',
            name='warehouse',
        ),
        migrations.RemoveField(
            model_name='textilestock',
            name='warehouse_product',
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='textile_stock',
            field=models.ForeignKey(limit_choices_to={'product__product_type': 'fabric'}, on_delete=django.db.models.deletion.CASCADE, to='warehouses.stockitem', verbose_name='مخزون القماش'),
        ),
    ]
