# Generated by Django 5.2.3 on 2025-07-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_remove_finalproduct_finishing_process_and_more'),
        ('warehouses', '0008_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinalProduct',
        ),
        migrations.DeleteModel(
            name='FinishedProduct',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
        migrations.DeleteModel(
            name='TextileStock',
        ),
    ]
