# Generated by Django 5.2.3 on 2025-07-07 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_delete_finalproduct_delete_finishedproduct_and_more'),
        ('warehouses', '0010_remove_product_size_group_product_size_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalmanufacturer',
            name='price_per_piece',
        ),
        migrations.CreateModel(
            name='ManufacturerProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر القطعة')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='production.externalmanufacturer', verbose_name='المصنع')),
                ('product', models.ForeignKey(limit_choices_to={'product_type': 'finished'}, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_prices', to='warehouses.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'سعر منتج المصنع',
                'verbose_name_plural': 'أسعار منتجات المصنع',
                'ordering': ['manufacturer', 'product__name'],
                'unique_together': {('manufacturer', 'product')},
            },
        ),
    ]
