# Generated by Django 5.2.3 on 2025-07-07 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_remove_externalmanufacturer_price_per_piece_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dyeingprocess',
            name='dyeing_cost_per_piece',
        ),
    ]
