# Generated by Django 5.2.3 on 2025-07-09 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_remove_dyeingprocess_dyeing_cost_per_piece'),
        ('warehouses', '0010_remove_product_size_group_product_size_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='size_group',
            new_name='size_groups',
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterials',
            unique_together={('product', 'size_groups', 'version')},
        ),
    ]
