# Generated by Django 5.2.3 on 2025-07-09 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_rename_size_group_billofmaterials_size_groups_and_more'),
        ('warehouses', '0010_remove_product_size_group_product_size_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='size_groups',
            new_name='size_group',
        ),
        migrations.AlterUniqueTogether(
            name='billofmaterials',
            unique_together={('product', 'size_group', 'version')},
        ),
    ]
