# Generated by Django 5.2.3 on 2025-08-13 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_rename_size_groups_billofmaterials_size_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishingprocess',
            name='receipt_history',
            field=models.JSONField(blank=True, default=list, verbose_name='سجل دفعات الاستلام'),
        ),
    ]
