# Generated by Django 5.2.3 on 2025-07-14 09:23

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='كود الموظف (على جهاز البصمة)')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم بالكامل')),
                ('job_title', models.CharField(max_length=100, verbose_name='المسمى الوظيفي')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('gender', models.CharField(choices=[('Male', 'ذكر'), ('Female', 'أنثى')], max_length=10, verbose_name='الجنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='الراتب')),
                ('work_start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='وقت بدء العمل')),
                ('work_end_time', models.TimeField(default=datetime.time(17, 0), verbose_name='وقت انتهاء العمل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='صورة الموظف')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم المرتبط')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفين',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'حضور وانصراف',
                'verbose_name_plural': 'سجلات الحضور والانصراف',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
