# Generated by Django 5.2.3 on 2025-07-14 10:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='salary',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='الراتب'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_start_time',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='وقت بدء العمل'),
        ),
    ]
