# Generated by Django 5.2.3 on 2025-07-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_salary_alter_employee_work_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_back_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_ids/', verbose_name='صورة ظهر البطاقة'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_face_image',
            field=models.ImageField(blank=True, null=True, upload_to='employee_ids/', verbose_name='صورة وجه البطاقة'),
        ),
    ]
