# Generated by Django 5.2.3 on 2025-06-29 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(blank=True, verbose_name='القيمة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'إعداد',
                'verbose_name_plural': 'الإعدادات',
            },
        ),
    ]
