# Generated by Django 5.2.3 on 2025-08-13 11:39

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('customer_type', models.CharField(choices=[('INDIVIDUAL', 'فرد'), ('COMPANY', 'شركة')], default='INDIVIDUAL', max_length=10, verbose_name='نوع العميل')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(help_text='مثال: +201012345678', max_length=128, region=None, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='البريد الإلكتروني')),
                ('address_line_1', models.CharField(blank=True, max_length=255, verbose_name='العنوان (سطر 1)')),
                ('address_line_2', models.CharField(blank=True, max_length=255, verbose_name='العنوان (سطر 2)')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='المدينة')),
                ('governorate', models.CharField(blank=True, max_length=100, verbose_name='المحافظة')),
                ('country', models.CharField(default='Egypt', max_length=100, verbose_name='الدولة')),
                ('company_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('CALL', 'مكالمة'), ('EMAIL', 'بريد إلكتروني'), ('MEETING', 'اجتماع'), ('NOTE', 'ملاحظة'), ('WHATSAPP', 'واتساب')], max_length=10, verbose_name='نوع التفاعل')),
                ('interaction_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التفاعل')),
                ('summary', models.TextField(verbose_name='ملخص التفاعل')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.customer', verbose_name='العميل')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفاعل',
                'verbose_name_plural': 'التفاعلات',
                'ordering': ['-interaction_date'],
            },
        ),
    ]
