# Generated by Django 5.2.3 on 2025-06-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together=set(),
        ),
    ]
