# Generated by Django 5.2.3 on 2025-06-19 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_alter_stockitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockitem',
            unique_together={('warehouse', 'product')},
        ),
    ]
