# Generated by Django 5.2.3 on 2025-06-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0003_alter_stockitem_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الوحدة')),
                ('symbol', models.CharField(max_length=10, verbose_name='الرمز')),
                ('is_base_unit', models.BooleanField(default=False, verbose_name='وحدة أساسية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='معامل التحويل')),
                ('from_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_from', to='warehouses.unit', verbose_name='من الوحدة')),
                ('to_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions_to', to='warehouses.unit', verbose_name='إلى الوحدة')),
            ],
            options={
                'verbose_name': 'تحويل وحدة',
                'verbose_name_plural': 'تحويلات الوحدات',
                'unique_together': {('from_unit', 'to_unit')},
            },
        ),
    ]
