# Generated by Django 5.2.3 on 2025-06-19 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0004_create_unit_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouses.unit', verbose_name='الوحدة الجديدة'),
        ),
    ]
