# Generated by Django 5.2.3 on 2025-06-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0005_add_unit_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='type',
            field=models.CharField(choices=[('raw_materials', 'مواد خام'), ('fabric', 'اقمشه'), ('finished_product', 'منتج نهائي'), ('other', 'اخري')], default='other', max_length=20, verbose_name='نوع المخزن'),
        ),
    ]
