# Generated by Django 5.2.3 on 2025-07-01 13:59
# Corrected order of operations by Gemini

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # These are the original, correct dependencies
        ('production', '0018_remove_finalproduct_finishing_process_and_more'),
        ('warehouses', '0007_productbatch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # --- THE FIX IS HERE: The operations have been re-ordered ---

        # 1. First, we add all the necessary fields to the models.
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الألوان المتاحة'),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_quantity_per_piece',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='كمية القماش للقطعة'),
        ),
        migrations.AddField(
            model_name='product',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=10, null=True, verbose_name='درجة الجودة'),
        ),
        migrations.AddField(
            model_name='product',
            name='size_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.sizegroup', verbose_name='مجموعة المقاسات'),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='العرض (سم)'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='production_finishing_source',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_batch', to='production.finishingprocess'),
        ),
        migrations.AddField(
            model_name='productbatch',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='warehouses.stockitem', verbose_name='عنصر المخزون'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Location / الموقع'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_type',
            field=models.CharField(choices=[('textile', 'Textile Warehouse / مخزن أقمشة'), ('finished_goods', 'Finished Goods Warehouse / مخزن منتجات نهائية'), ('components', 'Components Warehouse / مخزن مكونات'), ('other', 'Other / أخرى')], default='other', max_length=20, verbose_name='Warehouse Type / نوع المخزن'),
        ),
        
        # 2. Now that the 'stock' field exists on ProductBatch, we can apply the unique constraint.
        migrations.AlterUniqueTogether(
            name='productbatch',
            unique_together={('stock', 'batch_number')},
        ),

        # 3. Perform all other alterations and removals.
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Warehouse', 'verbose_name_plural': 'Warehouses'},
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='code',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='type',
        ),
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='سعر البيع'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At / تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description / الوصف'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active / نشط'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Manager / المدير'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Warehouse Name / اسم المخزن'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated / آخر تعديل'),
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='final_product_source',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productbatch',
            name='warehouse',
        ),
    ]
