# Generated by Django 5.2.3 on 2025-07-03 13:39

from django.db import migrations, models

def generate_unique_codes_for_existing_warehouses(apps, schema_editor):
    """
    Populates the new 'code' field with a unique, sequential code
    for all existing Warehouse instances.
    """
    Warehouse = apps.get_model('warehouses', 'Warehouse')
    # Loop through all existing warehouses and assign a code like W-0001, W-0002, etc.
    for index, warehouse in enumerate(Warehouse.objects.all()):
        # The code format is 'W-' followed by a zero-padded number.
        warehouse.code = f"W-{index + 1:04d}"
        warehouse.save(update_fields=['code'])


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0008_alter_warehouse_options_and_more'),
    ]

    operations = [
        # Step 1: Add the 'code' field but allow it to be null temporarily.
        # This prevents the UNIQUE constraint error on existing rows.
        migrations.AddField(
            model_name='warehouse',
            name='code',
            field=models.CharField(
                blank=True, 
                max_length=20, 
                null=True, # Allow null values for this step
                verbose_name='Warehouse Code / كود المخزن'
            ),
        ),
        # Step 2: Run the Python function to populate unique codes for all existing rows.
        migrations.RunPython(
            generate_unique_codes_for_existing_warehouses, 
            reverse_code=migrations.RunPython.noop # No action needed if migrating backwards
        ),
        # Step 3: Now that all rows have unique codes, alter the field to enforce
        # the UNIQUE constraint and make it non-nullable as intended.
        migrations.AlterField(
            model_name='warehouse',
            name='code',
            field=models.CharField(
                blank=True, 
                max_length=20, 
                unique=True, # Enforce uniqueness now
                verbose_name='Warehouse Code / كود المخزن'
            ),
        ),
    ]
