# Generated by Django 5.2.3 on 2025-07-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_delete_finalproduct_delete_finishedproduct_and_more'),
        ('warehouses', '0009_warehouse_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size_group',
        ),
        migrations.AddField(
            model_name='product',
            name='size_groups',
            field=models.ManyToManyField(blank=True, to='production.sizegroup', verbose_name='مجموعات المقاسات المتاحة'),
        ),
    ]
