# Generated by Django 5.2.3 on 2025-08-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0010_remove_product_size_group_product_size_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='سعر البيع'),
        ),
    ]
