# Generated by Django 5.2.3 on 2025-08-24 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, editable=False, max_length=50, unique=True, verbose_name='رقم الفاتورة'),
        ),
    ]
