# Generated by Django 5.2.3 on 2025-08-25 06:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('sales', '0002_alter_salesinvoice_invoice_number'),
        ('warehouses', '0010_remove_product_size_group_product_size_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoiceitem',
            options={'verbose_name': 'بند فاتورة', 'verbose_name_plural': 'بنود الفواتير'},
        ),
        migrations.AlterModelOptions(
            name='salesinvoice',
            options={'ordering': ['-issue_date', '-invoice_number'], 'verbose_name': 'فاتورة مبيعات', 'verbose_name_plural': 'فواتير المبيعات'},
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='payment_terms',
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='pricelistitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouses.product', verbose_name='المنتج'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer', verbose_name='العميل'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الفاتورة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'مسودة'), ('PENDING', 'معلقة'), ('PAID', 'مدفوعة'), ('CANCELLED', 'ملغاة')], default='PENDING', max_length=10, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الإجمالي الفرعي'),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='warehouses.warehouse', verbose_name='المخزن'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'نقدي'), ('VISA', 'فيزا'), ('SMART_WALLET', 'محفظة ذكية'), ('INSTAPAY', 'إنستا باي'), ('BANK_TRANSFER', 'تحويل بنكي'), ('CHEQUE', 'شيك')], max_length=20, verbose_name='طريقة الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الدفع')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='رقم المعاملة')),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الشيك')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salesinvoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
    ]
