# Generated by Django 5.0 on 2025-08-25 12:00

from django.db import migrations, models
import uuid

def gen_uuid(apps, schema_editor):
    SalesInvoice = apps.get_model('sales', 'SalesInvoice')
    for row in SalesInvoice.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_alter_invoiceitem_options_alter_salesinvoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesinvoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID', null=True),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='salesinvoice',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='UUID', unique=True, editable=False),
        ),
    ]
